SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: location_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.location_enum AS ENUM (
    'deck',
    'hand',
    'discard',
    'table'
);


--
-- Name: phase_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.phase_enum AS ENUM (
    'declared',
    'reacted_to',
    'started',
    'resolved',
    'failed'
);


--
-- Name: resolution_timing_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.resolution_timing_enum AS ENUM (
    'before',
    'after'
);


--
-- Name: target_type_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.target_type_enum AS ENUM (
    'enemy',
    'ally',
    'self',
    'card',
    'next_draw'
);


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: action_card_targets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.action_card_targets (
    id bigint NOT NULL,
    action_id bigint NOT NULL,
    target_card_id bigint NOT NULL,
    created_at timestamp(6) without time zone DEFAULT now() NOT NULL,
    updated_at timestamp(6) without time zone DEFAULT now() NOT NULL
);


--
-- Name: action_card_targets_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.action_card_targets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: action_card_targets_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.action_card_targets_id_seq OWNED BY public.action_card_targets.id;


--
-- Name: action_character_targets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.action_character_targets (
    id bigint NOT NULL,
    action_id bigint NOT NULL,
    target_character_id bigint NOT NULL,
    created_at timestamp(6) without time zone DEFAULT now() NOT NULL,
    updated_at timestamp(6) without time zone DEFAULT now() NOT NULL
);


--
-- Name: action_character_targets_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.action_character_targets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.action_character_targets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: actions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.actions (
    id bigint NOT NULL,
    game_id bigint NOT NULL,
    card_id bigint NOT NULL,
    source_id bigint NOT NULL,
    trigger_id bigint,
    phase public.phase_enum DEFAULT 'declared'::public.phase_enum NOT NULL,
    resolution_timing public.resolution_timing_enum,
    is_free boolean DEFAULT false NOT NULL,
    declarability_key character varying NOT NULL,
    tick_condition_key character varying NOT NULL,
    tick_effect_key character varying NOT NULL,
    max_tick_count integer NOT NULL,
    created_at timestamp(6) without time zone DEFAULT now() NOT NULL,
    updated_at timestamp(6) without time zone DEFAULT now() NOT NULL
);


--
-- Name: actions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.actions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.actions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ar_internal_metadata; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ar_internal_metadata (
    key character varying NOT NULL,
    value character varying,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);


--
-- Name: cards; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cards (
    id bigint NOT NULL,
    owner_character_id bigint NOT NULL,
    template_id bigint NOT NULL,
    location public.location_enum DEFAULT 'deck'::public.location_enum NOT NULL,
    "position" integer DEFAULT 0 NOT NULL, -- TODO: add a uniqueness index on (owner_character_id, location, position)
    created_at timestamp(6) without time zone DEFAULT now() NOT NULL,
    updated_at timestamp(6) without time zone DEFAULT now() NOT NULL,
    target_type_enum public.target_type_enum,
    target_count_min integer,
    target_count_max integer,
    target_condition_key character varying
);


--
-- Name: cards_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cards ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cards_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: characters; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.characters (
    id bigint NOT NULL,
    game_id bigint NOT NULL,
    name character varying NOT NULL,
    health integer DEFAULT 100 NOT NULL,
    actions_remaining integer DEFAULT 2 NOT NULL,
    reactions_remaining integer DEFAULT 2 NOT NULL,
    created_at timestamp(6) without time zone DEFAULT now() NOT NULL,
    updated_at timestamp(6) without time zone DEFAULT now() NOT NULL
);


--
-- Name: characters_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.characters ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.characters_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: games; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.games (
    id bigint NOT NULL,
    current_character_id bigint,
    created_at timestamp(6) without time zone DEFAULT now() NOT NULL,
    updated_at timestamp(6) without time zone DEFAULT now() NOT NULL
);


--
-- Name: games_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.games ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.games_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    version character varying NOT NULL
);


--
-- Name: templates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.templates (
    id bigint NOT NULL,
    name character varying NOT NULL,
    description text NOT NULL,
    resolution_timing public.resolution_timing_enum NOT NULL,
    is_free boolean DEFAULT false NOT NULL,
    declarability_key character varying NOT NULL,
    tick_condition_key character varying NOT NULL,
    tick_effect_key character varying NOT NULL,
    max_tick_count integer NOT NULL,
    created_at timestamp(6) without time zone DEFAULT now() NOT NULL,
    updated_at timestamp(6) without time zone DEFAULT now() NOT NULL,
    target_type_enum public.target_type_enum DEFAULT 'enemy'::public.target_type_enum NOT NULL,
    target_count_min integer DEFAULT 0 NOT NULL,
    target_count_max integer DEFAULT 1 NOT NULL,
    target_condition_key character varying DEFAULT ''::character varying NOT NULL
);


--
-- Name: templates_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.templates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.templates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: action_card_targets id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.action_card_targets ALTER COLUMN id SET DEFAULT nextval('public.action_card_targets_id_seq'::regclass);


--
-- Name: action_card_targets action_card_targets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.action_card_targets
    ADD CONSTRAINT action_card_targets_pkey PRIMARY KEY (id);


--
-- Name: action_character_targets action_character_targets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.action_character_targets
    ADD CONSTRAINT action_character_targets_pkey PRIMARY KEY (id);


--
-- Name: actions actions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.actions
    ADD CONSTRAINT actions_pkey PRIMARY KEY (id);


--
-- Name: ar_internal_metadata ar_internal_metadata_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ar_internal_metadata
    ADD CONSTRAINT ar_internal_metadata_pkey PRIMARY KEY (key);


--
-- Name: cards cards_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cards
    ADD CONSTRAINT cards_pkey PRIMARY KEY (id);


--
-- Name: characters characters_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.characters
    ADD CONSTRAINT characters_pkey PRIMARY KEY (id);


--
-- Name: games games_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.games
    ADD CONSTRAINT games_pkey PRIMARY KEY (id);


--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (version);


--
-- Name: templates templates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.templates
    ADD CONSTRAINT templates_pkey PRIMARY KEY (id);


--
-- Name: index_action_card_targets_on_action_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_action_card_targets_on_action_id ON public.action_card_targets USING btree (action_id);


--
-- Name: index_action_card_targets_on_target_card_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_action_card_targets_on_target_card_id ON public.action_card_targets USING btree (target_card_id);


--
-- Name: index_action_character_targets_on_action_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_action_character_targets_on_action_id ON public.action_character_targets USING btree (action_id);


--
-- Name: index_action_character_targets_on_target_character_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_action_character_targets_on_target_character_id ON public.action_character_targets USING btree (target_character_id);


--
-- Name: index_actions_on_card_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_actions_on_card_id ON public.actions USING btree (card_id);


--
-- Name: index_actions_on_game_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_actions_on_game_id ON public.actions USING btree (game_id);


--
-- Name: index_actions_on_game_id_phase; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_actions_on_game_id_phase ON public.actions USING btree (game_id, phase);


--
-- Name: index_actions_on_phase; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_actions_on_phase ON public.actions USING btree (phase);


--
-- Name: index_actions_on_source_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_actions_on_source_id ON public.actions USING btree (source_id);


--
-- Name: index_actions_on_trigger_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_actions_on_trigger_id ON public.actions USING btree (trigger_id);


--
-- Name: index_cards_on_owner_character_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_cards_on_owner_character_id ON public.cards USING btree (owner_character_id);


--
-- Name: index_cards_on_template_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_cards_on_template_id ON public.cards USING btree (template_id);


--
-- Name: index_characters_on_game_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_characters_on_game_id ON public.characters USING btree (game_id);


--
-- Name: index_templates_on_name; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX index_templates_on_name ON public.templates USING btree (name);


--
-- Name: action_character_targets action_targets_action_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.action_character_targets
    ADD CONSTRAINT action_targets_action_id_fkey FOREIGN KEY (action_id) REFERENCES public.actions(id) ON DELETE CASCADE;


--
-- Name: action_character_targets action_targets_target_character_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.action_character_targets
    ADD CONSTRAINT action_targets_target_character_id_fkey FOREIGN KEY (target_character_id) REFERENCES public.characters(id) ON DELETE CASCADE;


--
-- Name: actions actions_card_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.actions
    ADD CONSTRAINT actions_card_id_fkey FOREIGN KEY (card_id) REFERENCES public.cards(id) ON DELETE CASCADE;


--
-- Name: actions actions_game_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.actions
    ADD CONSTRAINT actions_game_id_fkey FOREIGN KEY (game_id) REFERENCES public.games(id) ON DELETE CASCADE;


--
-- Name: actions actions_source_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.actions
    ADD CONSTRAINT actions_source_id_fkey FOREIGN KEY (source_id) REFERENCES public.characters(id) ON DELETE CASCADE;


--
-- Name: actions actions_trigger_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.actions
    ADD CONSTRAINT actions_trigger_id_fkey FOREIGN KEY (trigger_id) REFERENCES public.actions(id) ON DELETE SET NULL;


--
-- Name: cards cards_owner_character_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cards
    ADD CONSTRAINT cards_owner_character_id_fkey FOREIGN KEY (owner_character_id) REFERENCES public.characters(id) ON DELETE CASCADE;


--
-- Name: cards cards_template_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cards
    ADD CONSTRAINT cards_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.templates(id) ON DELETE RESTRICT;


--
-- Name: characters characters_game_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.characters
    ADD CONSTRAINT characters_game_id_fkey FOREIGN KEY (game_id) REFERENCES public.games(id) ON DELETE CASCADE;


--
-- Name: games fk_games_current_character_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.games
    ADD CONSTRAINT fk_games_current_character_id FOREIGN KEY (current_character_id) REFERENCES public.characters(id) ON DELETE RESTRICT;


--
-- Name: action_card_targets fk_rails_605fd4a30e; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.action_card_targets
    ADD CONSTRAINT fk_rails_605fd4a30e FOREIGN KEY (action_id) REFERENCES public.actions(id) ON DELETE CASCADE;


--
-- Name: action_card_targets fk_rails_afb2172704; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.action_card_targets
    ADD CONSTRAINT fk_rails_afb2172704 FOREIGN KEY (target_card_id) REFERENCES public.cards(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

SET search_path TO "$user", public;

INSERT INTO "schema_migrations" (version) VALUES
('20250526161111'),
('20250526150956'),
('20250524225229');

