class CreateInitialSchema < ActiveRecord::Migration[8.0]
  def up
    sql_commands = <<-SQL
      CREATE TYPE phase_enum AS ENUM (
        'declared',
        'reacted_to',
        'started',
        'resolved',
        'failed'
      );

      CREATE TYPE resolution_timing_enum AS ENUM (
        'before',
        'after'
      );

      CREATE TYPE location_enum AS ENUM (
        'deck',
        'hand',
        'discard',
        'table'
      );

      CREATE TABLE templates (
        id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name varchar NOT NULL,
        description text NOT NULL,
        resolution_timing resolution_timing_enum NOT NULL,
        is_free boolean DEFAULT false NOT NULL,
        declarability_key varchar NOT NULL,
        tick_condition_key varchar NOT NULL,
        tick_effect_key varchar NOT NULL,
        max_tick_count integer NOT NULL,
        created_at timestamp(6) without time zone NOT NULL DEFAULT NOW(),
        updated_at timestamp(6) without time zone NOT NULL DEFAULT NOW()
      );
      CREATE UNIQUE INDEX index_templates_on_name ON templates (name);

      CREATE TABLE games (
        id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        current_character_id bigint,
        created_at timestamp(6) without time zone NOT NULL DEFAULT NOW(),
        updated_at timestamp(6) without time zone NOT NULL DEFAULT NOW()
      );

      CREATE TABLE characters (
        id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        game_id bigint NOT NULL REFERENCES games(id) ON DELETE CASCADE,
        name varchar NOT NULL,
        health integer DEFAULT 100 NOT NULL,
        actions_remaining integer DEFAULT 2 NOT NULL,
        reactions_remaining integer DEFAULT 2 NOT NULL,
        created_at timestamp(6) without time zone NOT NULL DEFAULT NOW(),
        updated_at timestamp(6) without time zone NOT NULL DEFAULT NOW()
      );
      CREATE INDEX index_characters_on_game_id ON characters (game_id);

      ALTER TABLE games ADD CONSTRAINT fk_games_current_character_id FOREIGN KEY (current_character_id) REFERENCES characters(id) ON DELETE RESTRICT;

      CREATE TABLE cards (
        id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        owner_character_id bigint NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
        template_id bigint NOT NULL REFERENCES templates(id) ON DELETE RESTRICT,
        location location_enum NOT NULL DEFAULT 'deck',
        position integer NOT NULL DEFAULT 0,
        created_at timestamp(6) without time zone NOT NULL DEFAULT NOW(),
        updated_at timestamp(6) without time zone NOT NULL DEFAULT NOW()
      );
      CREATE INDEX index_cards_on_owner_character_id ON cards (owner_character_id);
      CREATE INDEX index_cards_on_template_id ON cards (template_id);

      CREATE TABLE actions (
        id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        game_id bigint NOT NULL REFERENCES games(id) ON DELETE CASCADE,
        card_id bigint NOT NULL REFERENCES cards(id) ON DELETE CASCADE,
        source_id bigint NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
        trigger_id bigint REFERENCES actions(id) ON DELETE SET NULL,
        phase phase_enum DEFAULT 'declared' NOT NULL,
        resolution_timing resolution_timing_enum,
        is_free boolean DEFAULT false NOT NULL,
        declarability_key varchar NOT NULL,
        tick_condition_key varchar NOT NULL,
        tick_effect_key varchar NOT NULL,
        max_tick_count integer NOT NULL,
        created_at timestamp(6) without time zone NOT NULL DEFAULT NOW(),
        updated_at timestamp(6) without time zone NOT NULL DEFAULT NOW()
      );
      CREATE INDEX index_actions_on_game_id ON actions (game_id);
      CREATE INDEX index_actions_on_card_id ON actions (card_id);
      CREATE INDEX index_actions_on_source_id ON actions (source_id);
      CREATE INDEX index_actions_on_trigger_id ON actions (trigger_id);
      CREATE INDEX index_actions_on_phase ON actions (phase);
      CREATE INDEX index_actions_on_game_id_phase ON actions (game_id, phase);

      CREATE TABLE action_targets (
        id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        action_id bigint NOT NULL REFERENCES actions(id) ON DELETE CASCADE,
        target_character_id bigint NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
        created_at timestamp(6) without time zone NOT NULL DEFAULT NOW(),
        updated_at timestamp(6) without time zone NOT NULL DEFAULT NOW()
      );
      CREATE INDEX index_action_targets_on_action_id ON action_targets (action_id);
      CREATE INDEX index_action_targets_on_target_character_id ON action_targets (target_character_id);
    SQL

    execute sql_commands
  end

  def down
    execute <<-SQL
      DROP TABLE IF EXISTS action_targets CASCADE;
      DROP TABLE IF EXISTS actions CASCADE;
      DROP TABLE IF EXISTS cards CASCADE;
      -- Need to remove the FK constraint on games before dropping characters
      ALTER TABLE games DROP CONSTRAINT IF EXISTS fk_games_current_character_id;
      DROP TABLE IF EXISTS characters CASCADE;
      DROP TABLE IF EXISTS games CASCADE;
      DROP TABLE IF EXISTS templates CASCADE;

      DROP TYPE IF EXISTS location_enum;
      DROP TYPE IF EXISTS resolution_timing_enum;
      DROP TYPE IF EXISTS phase_enum;
    SQL
  end
end
